1_exec_f:1_exec_f.c
	gcc 1_exec_f.c -o 1_exec_f

2_2th_sim:2_2th_sim.c
	gcc 2_2th_sim.c -o 2_2th_sim

3_impl_kill:3_impl_kill.c
	gcc 3_impl_kill.c -o 3_impl_kill

4charthread:4charthread.c
	gcc 4charthread.c -o 4charthread

5c_dir1:5c_dir1.c
	gcc 5c_dir1.c -o 5c_dir1

7_ls:7_ls.c
	gcc 7_ls.c -o 7_ls

8create:8create.c
	gcc 8create.c -o 8create

9_sigbeh:9_sigbeh.c
	gcc 9_sigbeh.c -o 9_sigbeh

10_swap:10_swap.c
	gcc 10_swap.c -o 10_swap

11_th_wo_mut:11_th_wo_mut.c
	gcc 11_th_wo_mut.c -o 11_th_wo_mut

12_mesg_ptoc:12_mesg_ptoc.c
	gcc 12_mesg_ptoc.c -o 12_mesg_ptoc


16thrd_cond:16thrd_cond.c
	gcc 16thrd_cond -o 16thrd_cond


	



