1_exec_f:1_exec_f.c
	gcc 1_exec_f.c -o 1_exec_f

2_2th_sim:2_2th_sim.c
	gcc 2_2th_sim.c -o 2_2th_sim

3_impl_kill:3_impl_kill.c
	gcc 3_impl_kill.c -o 3_impl_kill

4charthread:4charthread.c
	gcc 4charthread.c -o 4charthread

5c_dir1:5c_dir1.c
	gcc 5c_dir1.c -o 5c_dir1

8create:8create.c
	gcc 8create.c -o 8create

9_sigbeh:9_sigbeh.c
	gcc 9_sigbeh.c -o 9_sigbeh

10swap_file:10swap_file.c
	gcc 10swap_file.c -o 10swap_file

11:11.c
	gcc 11.c -o 11

12:12.c
	gcc 12.c -o 12

15thrd_cond:15thrd_cond.c
	gcc 15thrd_cond -o 15thrd_cond


	



